import type { ClientConfig } from "./types.js";

export const DEFAULT_CONFIG: ClientConfig = {
  dbPath: "xtrawl_state.db",
  concurrency: 5,
  saveDir: "outputs",
  saveFormat: "csv",
  apiHttpMode: "auto",
  dailyRequestsLimit: 30,
  dailyTweetsLimit: 600,
  maxEmptyPages: 1,
  apiPageSize: 20,
  searchSplits: 5,
  schedulerMinIntervalMs: 300_000,
  minDelayMs: 2_000,
  leaseTtlMs: 120_000,
  leaseHeartbeatMs: 30_000,
  cooldownDefaultMs: 120_000,
  transientCooldownMs: 120_000,
  authCooldownMs: 30 * 24 * 60 * 60 * 1_000,
  cooldownJitterMs: 10_000,
  requestsPerMinute: 30,
  retryBaseMs: 1_000,
  retryMaxMs: 30_000,
  maxTaskAttempts: 3,
  maxFallbackAttempts: 3,
  maxAccountSwitches: 2,
  proxyCheckOnLease: true,
  proxyCheckUrl: "https://x.com/robots.txt",
  proxyCheckTimeoutMs: 10_000,
  profileTimelineAllowAnonymous: false,
  allowedManifestOrigins: [],
  manifestTtlMs: 3_600_000,
  manifestUpdateOnInit: false,
  manifestScrapeOnInit: false,
  transactionIdEnabled: true,
  transactionIdTtlMs: 6 * 60 * 60 * 1_000,
  strict: false,
  bearerToken:
    "AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA",
};
